### ISSUE TITLE
Äquivalenzklassen R1

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-dmg#18]
Kannst du das mal kurz anschauen? Verstehst du das? Habe keine Notizen dazu gefunden...

**Comment by fabwu** [comment]
Ich werds morgen mal anschauen. Bald sind wir durch... :hushed:

**Comment by fabwu** [comment]
Ich glaub das geht so bin mir aber auch nicht sicher. Ich glaub Bürgler hat das übersprungen.
